name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0-278.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  image_picker: ^1.2.0
  stripe_sdk: ^5.0.0
  flutter_local_notifications: ^19.4.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  uuid: ^4.0.0
  cloud_functions: ^6.0.1
  app_links: ^6.4.1
  firebase_app_check: ^0.4.0+1
  url_launcher: ^6.1.0 
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^11.5.0
  firebase_messaging: ^16.0.1
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/contracts/
  uses-material-design: true
